Repository DDD-Community/DDD-12-oi-Server, pull requests merged in 2025-08, with the labels that each got.

#56 ♻️ Refactor: 컨텐츠, 컨텐츠 스팟 스웨거 응답 추가
  src/main/java/com/ddd/oi/common/controller/SearchController.java
  src/main/java/com/ddd/oi/common/service/NaverSearchService.java
  src/main/java/com/ddd/oi/contents/controller/ContentsController.java
  src/main/java/com/ddd/oi/contents/controller/docs/ContentsControllerDocs.java
  src/main/java/com/ddd/oi/contents/domain/Contents.java
  src/main/java/com/ddd/oi/contents/dto/ContentsCreateRequest.java
  src/main/java/com/ddd/oi/contents/dto/ContentsResponse.java
  src/main/java/com/ddd/oi/contents/dto/ContentsUpdateRequest.java
  src/main/java/com/ddd/oi/contents/repository/ContentsRepository.java
  src/main/java/com/ddd/oi/contents/service/ContentsService.java
  src/main/java/com/ddd/oi/contents_image/controller/ContentsImageController.java
  src/main/java/com/ddd/oi/contents_image/domain/ContentsImage.java
  src/main/java/com/ddd/oi/contents_image/dto/ContentsImageRequest.java
  src/main/java/com/ddd/oi/contents_image/dto/ContentsImageResponse.java
  src/main/java/com/ddd/oi/contents_image/repository/ContentsImageRepository.java
  src/main/java/com/ddd/oi/contents_image/service/ContentsImageService.java
  src/main/java/com/ddd/oi/contents_spot/controller/ContentsSpotController.java
  src/main/java/com/ddd/oi/contents_spot/controller/docs/ContentsSpotControllerDocs.java
  src/main/java/com/ddd/oi/contents_spot/dto/ContentsSpotRequest.java
  src/main/java/com/ddd/oi/contents_spot/service/ContentsSpotService.java
Labels: REFACTOR

#64 ♻️ Refactor: Contents 주별 조회 API 추가, 최신/인기 필드 추가
  src/main/java/com/ddd/oi/contents/controller/ContentsController.java
  src/main/java/com/ddd/oi/contents/controller/docs/ContentsControllerDocs.java
  src/main/java/com/ddd/oi/contents/domain/Contents.java
  src/main/java/com/ddd/oi/contents/domain/enumType/BadgeType.java
  src/main/java/com/ddd/oi/contents/dto/ContentsCreateRequest.java
  src/main/java/com/ddd/oi/contents/dto/ContentsResponse.java
  src/main/java/com/ddd/oi/contents/dto/ContentsUpdateRequest.java
  src/main/java/com/ddd/oi/contents/repository/ContentsRepository.java
  src/main/java/com/ddd/oi/contents/service/ContentsService.java
Labels: REFACTOR

#66 ✨ Feat: FAQ, 공지사항 API 추가
  src/main/java/com/ddd/oi/faq/controller/FaqController.java
  src/main/java/com/ddd/oi/faq/controller/docs/FaqControllerDocs.java
  src/main/java/com/ddd/oi/faq/domain/Faq.java
  src/main/java/com/ddd/oi/faq/dto/FaqCreateRequest.java
  src/main/java/com/ddd/oi/faq/dto/FaqResponse.java
  src/main/java/com/ddd/oi/faq/dto/FaqUpdateRequest.java
  src/main/java/com/ddd/oi/faq/repository/FaqRepository.java
  src/main/java/com/ddd/oi/faq/service/FaqService.java
  src/main/java/com/ddd/oi/notice/controller/NoticeController.java
  src/main/java/com/ddd/oi/notice/controller/docs/NoticeControllerDocs.java
  src/main/java/com/ddd/oi/notice/domain/Notice.java
  src/main/java/com/ddd/oi/notice/dto/NoticeCreateRequest.java
  src/main/java/com/ddd/oi/notice/dto/NoticeResponse.java
  src/main/java/com/ddd/oi/notice/dto/NoticeUpdateRequest.java
  src/main/java/com/ddd/oi/notice/repository/NoticeRepository.java
  src/main/java/com/ddd/oi/notice/service/NoticeService.java
  src/main/java/com/ddd/oi/user/domain/User.java
  src/main/java/com/ddd/oi/user/dto/UserConverter.java
  src/main/java/com/ddd/oi/user/dto/UserResponseDTO.java
Labels: FEAT

#67 :recycle: refactor: 컨텐츠 조회 날짜구간 제거
  src/main/java/com/ddd/oi/contents/controller/ContentsController.java
  src/main/java/com/ddd/oi/contents/controller/docs/ContentsControllerDocs.java
Labels: REFACTOR

#71 🐛 Fix: 카카오 네이티브 Access Token 기반 프로필 조회 로직으로 수정 #69
  src/main/java/com/ddd/oi/auth/dto/profile/KakaoDTO.java
  src/main/java/com/ddd/oi/common/utils/KakaoUtil.java
Labels: FIX

#77 ✨ Feat: 페이지네이션 공통응답 객체 추가, 스케줄 디테일 Docs 분리
  src/main/java/com/ddd/oi/common/response/PageResponse.java
  src/main/java/com/ddd/oi/faq/controller/FaqController.java
  src/main/java/com/ddd/oi/faq/controller/docs/FaqControllerDocs.java
  src/main/java/com/ddd/oi/faq/service/FaqService.java
  src/main/java/com/ddd/oi/notice/controller/NoticeController.java
  src/main/java/com/ddd/oi/notice/controller/docs/NoticeControllerDocs.java
  src/main/java/com/ddd/oi/notice/service/NoticeService.java
  src/main/java/com/ddd/oi/schedule_detail/controller/ScheduleDetailController.java
  src/main/java/com/ddd/oi/schedule_detail/controller/docs/ScheduleDetailControllerDocs.java
Labels: FEAT
