Repository DDD-Community/DDD-12-oi-Server, pull requests merged in 2025-07, with the labels that each got.

#26 Feat/25
  build.gradle
  src/main/java/com/ddd/oi/common/config/CategoryColorMapping.java
  src/main/java/com/ddd/oi/common/config/CategoryMapping.java
  src/main/java/com/ddd/oi/common/config/NaverSearchConfig.java
  src/main/java/com/ddd/oi/common/config/RestTemplateConfig.java
  src/main/java/com/ddd/oi/common/config/S3Config.java
  src/main/java/com/ddd/oi/common/controller/S3Controller.java
  src/main/java/com/ddd/oi/common/controller/SearchController.java
  src/main/java/com/ddd/oi/common/response/ErrorCode.java
  src/main/java/com/ddd/oi/common/service/NaverSearchService.java
  src/main/java/com/ddd/oi/common/service/S3Service.java
  src/main/java/com/ddd/oi/contents/controller/ContentsController.java
  src/main/java/com/ddd/oi/contents/domain/Contents.java
  src/main/java/com/ddd/oi/contents/domain/enumType/ContentsTag.java
  src/main/java/com/ddd/oi/contents/dto/ContentsCreateRequest.java
  src/main/java/com/ddd/oi/contents/dto/ContentsResponse.java
  src/main/java/com/ddd/oi/contents/dto/ContentsUpdateRequest.java
  src/main/java/com/ddd/oi/contents/dto/PresignedUrlRequest.java
  src/main/java/com/ddd/oi/contents/dto/PresignedUrlResponse.java
  src/main/java/com/ddd/oi/contents/repository/ContentsRepository.java
  src/main/java/com/ddd/oi/contents/service/ContentsService.java
  src/main/java/com/ddd/oi/contents_image/domain/ContentsImage.java
  src/main/java/com/ddd/oi/contents_spot/controller/ContentsSpotController.java
  src/main/java/com/ddd/oi/contents_spot/domain/ContentsSpot.java
  src/main/java/com/ddd/oi/contents_spot/dto/ContentsSpotRequest.java
  src/main/java/com/ddd/oi/contents_spot/dto/ContentsSpotResponse.java
  src/main/java/com/ddd/oi/contents_spot/service/ContentsSpotService.java
  src/main/java/com/ddd/oi/schedule_detail/domain/ScheduleDetail.java
  src/main/java/com/ddd/oi/schedule_detail/dto/AutoCompleteResponse.java
  src/main/java/com/ddd/oi/schedule_detail/dto/CategoryDto.java
  src/main/java/com/ddd/oi/schedule_detail/dto/PlaceItem.java
  src/main/java/com/ddd/oi/schedule_detail/dto/SearchRequest.java
  src/main/java/com/ddd/oi/schedule_detail/dto/SearchResponse.java
  src/main/java/com/ddd/oi/schedule_detail/dto/request/CreateDetailRequest.java
  src/main/java/com/ddd/oi/schedule_detail/dto/request/UpdateDetailRequest.java
  src/test/java/com/ddd/oi/common/controller/SearchControllerTest.java
  src/test/java/com/ddd/oi/common/service/NaverSearchServiceTest.java
  src/test/java/com/ddd/oi/contents/controller/ContentsControllerTest.java
  src/test/java/com/ddd/oi/contents/dto/ContentsRequestTest.java
  src/test/java/com/ddd/oi/contents/service/ContentsServiceTest.java
  src/test/java/com/ddd/oi/contents_spot/controller/ContentsSpotControllerTest.java
  src/test/java/com/ddd/oi/contents_spot/dto/ContentsSpotRequestTest.java
  src/test/java/com/ddd/oi/contents_spot/service/ContentsSpotServiceTest.java
Labels: TEST, FEAT, REFACTOR

#27 ♻️ Refacotr: 검색 서비스 테스트에서 생성자 개수 누락 수정
  src/test/java/com/ddd/oi/common/controller/SearchControllerTest.java
  src/test/java/com/ddd/oi/common/service/NaverSearchServiceTest.java
Labels: FIX

#28 :bug: fix: 테스트 임시 주석처리
  src/main/java/com/ddd/oi/common/controller/SearchController.java
  src/main/java/com/ddd/oi/common/service/NaverSearchService.java
  src/test/java/com/ddd/oi/common/controller/SearchControllerTest.java
  src/test/java/com/ddd/oi/common/service/NaverSearchServiceTest.java
  src/test/java/com/ddd/oi/contents/service/ContentsServiceTest.java
Labels: FIX

#30 ♻️ Refactor: 세부 일정 dto 수정 #29
  src/main/java/com/ddd/oi/schedule_detail/controller/ScheduleDetailController.java
  src/main/java/com/ddd/oi/schedule_detail/dto/request/CreateDetailRequest.java
  src/main/java/com/ddd/oi/schedule_detail/dto/response/CreateScheduleDetailResponse.java
  src/main/java/com/ddd/oi/schedule_detail/dto/response/UpdateScheduleDetailResponse.java
  src/main/java/com/ddd/oi/schedule_detail/service/ScheduleDetailService.java
  src/test/java/com/ddd/oi/schedule_detail/controller/ScheduleDetailControllerTest.java
  src/test/java/com/ddd/oi/schedule_detail/dto/ScheduleDetailRequestTest.java
  src/test/java/com/ddd/oi/schedule_detail/service/ScheduleDetailServiceTest.java
Labels: PERF

#31 Revert "♻️ Refactor: 세부 일정 dto 수정 #29"
  src/main/java/com/ddd/oi/schedule_detail/controller/ScheduleDetailController.java
  src/main/java/com/ddd/oi/schedule_detail/dto/request/CreateDetailRequest.java
  src/main/java/com/ddd/oi/schedule_detail/dto/response/CreateScheduleDetailResponse.java
  src/main/java/com/ddd/oi/schedule_detail/dto/response/UpdateScheduleDetailResponse.java
  src/main/java/com/ddd/oi/schedule_detail/service/ScheduleDetailService.java
  src/test/java/com/ddd/oi/schedule_detail/controller/ScheduleDetailControllerTest.java
  src/test/java/com/ddd/oi/schedule_detail/dto/ScheduleDetailRequestTest.java
  src/test/java/com/ddd/oi/schedule_detail/service/ScheduleDetailServiceTest.java
Labels: PERF

#36 ♻️ Refactor: 세부 일정 여러개 생성, 응답값 카테고리 추가 완료
  src/main/java/com/ddd/oi/common/config/CategoryMapping.java
  src/main/java/com/ddd/oi/common/response/ErrorCode.java
  src/main/java/com/ddd/oi/schedule_detail/controller/ScheduleDetailController.java
  src/main/java/com/ddd/oi/schedule_detail/domain/ScheduleDetail.java
  src/main/java/com/ddd/oi/schedule_detail/dto/request/CreateDetailRequest.java
  src/main/java/com/ddd/oi/schedule_detail/dto/response/CreateScheduleDetailResponse.java
  src/main/java/com/ddd/oi/schedule_detail/dto/response/ScheduleDetailResponse.java
  src/main/java/com/ddd/oi/schedule_detail/dto/response/UpdateScheduleDetailResponse.java
  src/main/java/com/ddd/oi/schedule_detail/service/ScheduleDetailService.java
  src/test/java/com/ddd/oi/schedule_detail/controller/ScheduleDetailControllerTest.java
  src/test/java/com/ddd/oi/schedule_detail/dto/ScheduleDetailRequestTest.java
  src/test/java/com/ddd/oi/schedule_detail/service/ScheduleDetailServiceTest.java
Labels: FEAT, REFACTOR

#38 :bug: fix: 세부일정 수정시 category 수정 #29
  src/main/java/com/ddd/oi/schedule_detail/service/ScheduleDetailService.java
Labels: FIX

#40 ✨ Feat: 장소 검색시 위도 경도 값 변경로직 추가 완료
  src/main/java/com/ddd/oi/common/config/CategoryColorMapping.java
  src/main/java/com/ddd/oi/common/config/CategoryMapping.java
  src/main/java/com/ddd/oi/common/config/NaverMapConfig.java
  src/main/java/com/ddd/oi/common/service/NaverSearchService.java
  src/main/java/com/ddd/oi/schedule_detail/dto/PlaceItem.java
Labels: FEAT

#47 ♻️ Refactor: 홈 컨텐츠 API 리팩터링 완료
  src/main/java/com/ddd/oi/common/controller/S3Controller.java
  src/main/java/com/ddd/oi/contents/controller/ContentsController.java
  src/main/java/com/ddd/oi/contents/domain/Contents.java
  src/main/java/com/ddd/oi/contents/dto/ContentsResponse.java
  src/main/java/com/ddd/oi/contents/dto/PresignedUrlRequest.java
  src/main/java/com/ddd/oi/contents/service/ContentsService.java
  src/main/java/com/ddd/oi/contents_image/controller/ContentsImageController.java
  src/main/java/com/ddd/oi/contents_image/domain/ContentsImage.java
  src/main/java/com/ddd/oi/contents_image/dto/ContentsImageRequest.java
  src/main/java/com/ddd/oi/contents_image/dto/ContentsImageResponse.java
  src/main/java/com/ddd/oi/contents_image/service/ContentsImageService.java
  src/main/java/com/ddd/oi/contents_spot/controller/ContentsSpotController.java
  src/main/java/com/ddd/oi/contents_spot/domain/ContentsSpot.java
  src/main/java/com/ddd/oi/contents_spot/dto/ContentsSpotResponse.java
  src/main/java/com/ddd/oi/contents_spot/service/ContentsSpotService.java
Labels: FEAT, REFACTOR

#50 ✨ Feat: 컨텐츠 인기순, 추천순, 최신순 기능 추가
  src/main/java/com/ddd/oi/common/response/ErrorCode.java
  src/main/java/com/ddd/oi/common/utils/NaverUtil.java
  src/main/java/com/ddd/oi/contents/controller/ContentsController.java
  src/main/java/com/ddd/oi/contents/domain/Contents.java
  src/main/java/com/ddd/oi/contents/domain/enumType/ContentsTag.java
  src/main/java/com/ddd/oi/contents/dto/ContentsCreateRequest.java
  src/main/java/com/ddd/oi/contents/dto/ContentsResponse.java
  src/main/java/com/ddd/oi/contents/dto/ContentsUpdateRequest.java
  src/main/java/com/ddd/oi/contents/repository/ContentsRepository.java
  src/main/java/com/ddd/oi/contents/service/ContentsService.java
  src/test/java/com/ddd/oi/contents/controller/ContentsControllerTest.java
  src/test/java/com/ddd/oi/contents/dto/ContentsRequestTest.java
Labels: FEAT
