Repository DDD-Community/DDD-12-oi-Server, pull requests merged in 2025-06, with the labels that each got.

#9 :recycle: Refactor: Dev Server에서 Swagger 하게 변경
  src/main/java/com/ddd/oi/common/config/SwaggerConfig.java
Labels: CHORE

#11 ♻️ Refactor: 일정 리스트 조회 Api 정렬기능 추가
  .gitignore
  src/main/java/com/ddd/oi/common/controller/EnumController.java
  src/main/java/com/ddd/oi/common/controller/HealthController.java
  src/main/java/com/ddd/oi/contents/domain/Contents.java
  src/main/java/com/ddd/oi/schedule/domain/Schedule.java
  src/main/java/com/ddd/oi/schedule/domain/enumType/GroupTag.java
  src/main/java/com/ddd/oi/schedule/domain/enumType/Mobility.java
  src/main/java/com/ddd/oi/schedule/domain/enumType/ScheduleTag.java
  src/main/java/com/ddd/oi/schedule/dto/request/UpdateScheduleRequest.java
  src/main/java/com/ddd/oi/schedule/dto/response/CreateScheduleResponse.java
  src/main/java/com/ddd/oi/schedule/dto/response/ScheduleListResponse.java
  src/main/java/com/ddd/oi/schedule/dto/response/UpdateScheduleResponse.java
  src/main/java/com/ddd/oi/schedule/repository/ScheduleRepository.java
  src/main/java/com/ddd/oi/schedule/service/ScheduleService.java
  src/main/java/com/ddd/oi/schedule_detail/domain/ScheduleDetail.java
  src/main/java/com/ddd/oi/schedule_detail/dto/request/CreateDetailRequest.java
  src/main/java/com/ddd/oi/schedule_detail/dto/request/UpdateDetailRequest.java
  src/main/java/com/ddd/oi/schedule_detail/dto/response/ScheduleDetailResponse.java
  src/main/java/com/ddd/oi/schedule_detail/repository/ScheduleDetailRepository.java
  src/main/java/com/ddd/oi/schedule_detail/service/ScheduleDetailService.java
  src/main/java/com/ddd/oi/user/domain/User.java
Labels: FEAT, REFACTOR

#13 :bug: fix: Import 에러 해결
  src/main/java/com/ddd/oi/schedule/domain/Schedule.java
  src/main/java/com/ddd/oi/schedule/dto/request/CreateScheduleRequest.java
  src/main/java/com/ddd/oi/user/domain/User.java
Labels: FIX

#15 :bug: fix: 하루에 일정 3개 예외 경우로 수정 #14
  src/main/java/com/ddd/oi/common/exception/GlobalExceptionHandler.java
  src/main/java/com/ddd/oi/common/response/ErrorCode.java
  src/main/java/com/ddd/oi/schedule/dto/request/CreateScheduleRequest.java
  src/main/java/com/ddd/oi/schedule/dto/request/UpdateScheduleRequest.java
  src/main/java/com/ddd/oi/schedule/repository/ScheduleRepository.java
  src/main/java/com/ddd/oi/schedule/service/ScheduleService.java
  src/main/resources/logback-spring.xml
Labels: FIX

#17 :recycle: refactor: 일정 추가시 response값 수정 #14
  src/main/java/com/ddd/oi/schedule/dto/response/CreateScheduleResponse.java
  src/main/java/com/ddd/oi/schedule/service/ScheduleService.java
Labels: PERF

#19 🐛 fix: request값 수정 #14
  src/main/java/com/ddd/oi/schedule/dto/request/CreateScheduleRequest.java
Labels: FIX
